"""Explicit, schema-validated planning operations; writes only via review endpoint."""
import uuid
from fastapi import HTTPException
from fastapi.encoders import jsonable_encoder
from pydantic import BaseModel, Field
from sqlalchemy import select
from app.models.activity import Activity
from app.models.calendar import Calendar, CalendarBreak, CalendarException
from app.models.resource import Resource
from app.models.cost_element import CostElement
from app.models.schedule_period import SchedulePeriod
from app.models.schedule_variant import ScheduleVariant
from app.models.period import Period
from app.schemas.resource import ResourceCreate, ResourceUpdate
from app.schemas.calendar import CalendarCreate, CalendarUpdate, CalendarBreakCreate, CalendarBreakUpdate, CalendarExceptionCreate, CalendarExceptionUpdate
from app.schemas.activity import ActivityUpdate
from app.schemas.cost_element import CostElementCreate, CostElementUpdate
from app.schemas.schedule_period import SchedulePeriodUpdate
from app.services import resource, calendar, activity, cost_element, schedule_period

# No arbitrary endpoint/SQL execution. Existing services retain their validations,
# CPM recomputation and cost synchronisation behaviour.
REGISTRY = {
    "resource": (Resource, ResourceCreate, ResourceUpdate, resource.create_resource, resource.update_resource),
    "calendar": (Calendar, CalendarCreate, CalendarUpdate, calendar.create_calendar, calendar.update_calendar),
    "calendar_break": (CalendarBreak, CalendarBreakCreate, CalendarBreakUpdate, calendar.create_break, calendar.update_break),
    "calendar_exception": (CalendarException, CalendarExceptionCreate, CalendarExceptionUpdate, calendar.create_exception, calendar.update_exception),
    "cost_element": (CostElement, CostElementCreate, CostElementUpdate, cost_element.create_cost_element, cost_element.update_cost_element),
    "activity": (Activity, None, ActivityUpdate, None, activity.update_activity),
    "schedule_settings": (SchedulePeriod, None, SchedulePeriodUpdate, None, schedule_period.update_period),
}
HIDDEN = {"project_id", "period_id", "schedule_period_id", "freeze_status", "baseline_locked_flag", "finish", "amend_relationships", "animation_profile_id", "qs_signoff_name", "qs_signoff_date"}


def fields_for(entity, action):
    schema = REGISTRY[entity][1 if action == "create" else 2]
    if schema is None:
        raise HTTPException(422, "Use the activity proposal tool to create a schedule.")
    return schema, set(schema.model_fields) - HIDDEN


def operation_schema(entity, action):
    model, allowed = fields_for(entity, action)
    raw = model.model_json_schema()
    properties = {k: v for k, v in raw["properties"].items() if k in allowed}
    data = {"type": "object", "properties": properties, "additionalProperties": False,
            "required": [k for k in raw.get("required", []) if k in allowed]}
    result = {"type": "object", "properties": {
        "entity": {"type": "string", "enum": [entity]},
        "action": {"type": "string", "enum": [action]},
        "label": {"type": "string", "description": "Human-readable record name and reason; identify assumptions and rate units."},
        "record_id": {"type": "string", "format": "uuid"},
        "data": data}, "required": ["entity", "action", "label", "data"], "additionalProperties": False}
    if action == "update": result["required"].append("record_id")
    return result


PLANNING_TOOLS = [
    {"name": "get_planning_records", "description": "Read saved planning records with real IDs and fields, scoped to this project and selected periods. Paginate until next_offset is null. Read before editing; never guess IDs. Calendars include separate break/exception records. Computed schedule dates and float are read-only.",
     "input_schema": {"type": "object", "properties": {"entity": {"type": "string", "enum": list(REGISTRY)}, "offset": {"type": "integer", "minimum": 0}}, "required": ["entity"], "additionalProperties": False}},
    {"name": "propose_planning_changes", "description": "Propose create/edit planning records for explicit user review. NEVER writes directly. Create calendars, then breaks/holidays, resources with rates, then activities using propose_create_activities and resource assignments. Read back IDs after approval before dependent proposals. Edit activity codes/durations/calendars/constraints/progress and schedule start dates. Cost elements are independent allowances: avoid double counting costs already generated by resource assignments. Explain project-wide impact of default calendars or resource rate edits. No delete, lock or approval bypass operations.",
     "input_schema": {"type": "object", "properties": {"operations": {"type": "array", "minItems": 1, "maxItems": 100, "items": {"anyOf": [operation_schema(e, a) for e in REGISTRY for a in ("create", "update") if a == "update" or REGISTRY[e][1]]}}}, "required": ["operations"], "additionalProperties": False}},
]


async def scoped_query(db, entity, project_id, schedule_id, period_id):
    if entity not in REGISTRY: raise HTTPException(422, "Unsupported planning record")
    model = REGISTRY[entity][0]
    stmt = select(model)
    if entity in ("calendar_break", "calendar_exception"):
        return stmt.join(Calendar, model.calendar_id == Calendar.id).where(Calendar.project_id == project_id)
    if entity == "schedule_settings":
        return stmt.join(ScheduleVariant, SchedulePeriod.schedule_variant_id == ScheduleVariant.id).where(ScheduleVariant.project_id == project_id, SchedulePeriod.id == schedule_id)
    stmt = stmt.where(model.project_id == project_id)
    if entity == "activity": stmt = stmt.where(Activity.schedule_period_id == schedule_id)
    if entity == "cost_element": stmt = stmt.where(CostElement.period_id == period_id)
    return stmt


async def read_records(db, entity, project_id, schedule_id, period_id, offset=0):
    if not isinstance(offset, int) or offset < 0: raise HTTPException(422, "Invalid offset")
    if entity not in REGISTRY: raise HTTPException(422, "Unsupported planning record")
    model = REGISTRY[entity][0]
    stmt = await scoped_query(db, entity, project_id, schedule_id, period_id)
    rows = (await db.execute(stmt.order_by(model.id).offset(offset).limit(101))).scalars().all()
    records = [jsonable_encoder({c.name: getattr(row, c.name) for c in model.__table__.columns}) for row in rows[:100]]
    return {"records": records, "next_offset": offset + 100 if len(rows) > 100 else None}


class PlanningOperation(BaseModel):
    entity: str
    action: str
    label: str
    record_id: uuid.UUID | None = None
    data: dict


class PlanningApproval(BaseModel):
    project_id: uuid.UUID
    schedule_period_id: uuid.UUID | None = None
    period_id: uuid.UUID | None = None
    operations: list[PlanningOperation] = Field(max_length=100)


async def apply_operation(db, op, project_id, schedule_id, period_id):
    if op.entity not in REGISTRY or op.action not in ("create", "update"):
        raise HTTPException(422, "Unsupported planning operation")
    schema, allowed = fields_for(op.entity, op.action)
    if not op.data or set(op.data) - allowed:
        raise HTTPException(422, "Unsupported or empty planning fields")
    data = dict(op.data)
    model, _, _, create, update = REGISTRY[op.entity]
    if op.action == "update":
        stmt = await scoped_query(db, op.entity, project_id, schedule_id, period_id)
        row = (await db.execute(stmt.where(model.id == op.record_id))).scalar_one_or_none()
        if row is None: raise HTTPException(404, "Record not found in the selected project/period")
        if op.entity == "schedule_settings" and row.freeze_status != "live":
            raise HTTPException(409, "Cannot edit a frozen schedule")
    for key, target in (("calendar_id", "calendar"), ("parent_id", "activity")):
        if data.get(key):
            stmt = await scoped_query(db, target, project_id, schedule_id, period_id)
            ref = (await db.execute(stmt.where(REGISTRY[target][0].id == uuid.UUID(str(data[key]))))).scalar_one_or_none()
            if ref is None: raise HTTPException(404, "Referenced record is outside the selected project/period")
    if op.entity == "resource":
        kind = data.get("resource_type", getattr(row, "resource_type", None) if op.action == "update" else None)
        unit = data.get("unit", getattr(row, "unit", None) if op.action == "update" else None)
        if kind in ("labour", "equipment", "crew") and str(unit).lower() not in ("day", "days", "d"):
            raise HTTPException(422, "Time-based resource rates must be per working day; convert hourly quotes using paid hours and set unit to day.")
    if op.action == "create":
        if "project_id" in schema.model_fields: data["project_id"] = project_id
        if "period_id" in schema.model_fields:
            period = await db.get(Period, period_id) if period_id else None
            if period is None or period.project_id != project_id: raise HTTPException(422, "Select a reporting period first")
            data["period_id"] = period_id
        result = await create(db, schema.model_validate(data))
    else:
        result = await update(db, op.record_id, schema.model_validate(data))
    if op.entity == "resource" and op.action == "update":
        from app.models.resource_assignment import ResourceAssignment
        from app.services.cost_sync import sync_cost_elements_from_resources_bulk
        ids = (await db.execute(select(ResourceAssignment.activity_id).join(Activity, ResourceAssignment.activity_id == Activity.id)
               .join(SchedulePeriod, Activity.schedule_period_id == SchedulePeriod.id)
               .where(ResourceAssignment.resource_id == op.record_id, Activity.project_id == project_id,
                      SchedulePeriod.freeze_status == "live"))).scalars().all()
        await sync_cost_elements_from_resources_bulk(db, list(set(ids)))
        await db.commit()
        await db.refresh(result)
    if op.entity == "schedule_settings":
        from app.services.scheduling_cpm import recompute_schedule
        await recompute_schedule(db, op.record_id)
        await db.commit()
        await db.refresh(result)
    return {"id": str(result.id), "entity": op.entity, "action": op.action, "label": op.label}
