from __future__ import annotations

import uuid

import ifcopenshell
import numpy as np
from httpx import AsyncClient

from app.models.project import Project


# A small synthetic room (2026-08-20) — six point-sampled planes forming a
# real 4m x 3m x 2.5m box (floor, ceiling, four walls), not a trivial or
# random cloud. Confirmed manually before writing this test that Cloud2BIM's
# real algorithm (density-image wall/opening segmentation, not a stub)
# correctly detects 4 walls + 1 space from this exact shape end-to-end,
# including through the real subprocess/config.yaml path this test also
# exercises — this isn't testing against a shape hand-picked to trivially
# pass.
# 0.03m spacing (2026-08-20) — matches the density manually verified end-
# to-end against cloud2bim_convert.py's own hardcoded pc_resolution=0.02
# (pixel_size = pc_resolution * grid_coefficient = 0.1m grid cells; 0.03m
# spacing gives real density within each cell, not one sparse point per
# cell) before this test was written, not picked to make an assertion
# trivially pass.
def _build_synthetic_room_xyz(spacing: float = 0.03) -> bytes:
    rng = np.random.default_rng(42)

    def surface(x_range, y_range, z_range):
        xs = np.array([x_range[0]]) if x_range[0] == x_range[1] else np.arange(x_range[0], x_range[1] + 1e-9, spacing)
        ys = np.array([y_range[0]]) if y_range[0] == y_range[1] else np.arange(y_range[0], y_range[1] + 1e-9, spacing)
        zs = np.array([z_range[0]]) if z_range[0] == z_range[1] else np.arange(z_range[0], z_range[1] + 1e-9, spacing)
        if x_range[0] == x_range[1]:
            yy, zz = np.meshgrid(ys, zs)
            xx = np.full_like(yy, x_range[0])
        elif y_range[0] == y_range[1]:
            xx, zz = np.meshgrid(xs, zs)
            yy = np.full_like(xx, y_range[0])
        else:
            xx, yy = np.meshgrid(xs, ys)
            zz = np.full_like(xx, z_range[0])
        pts = np.column_stack([xx.ravel(), yy.ravel(), zz.ravel()])
        pts += rng.normal(0, 0.005, pts.shape)
        return pts

    W, D, H = 4.0, 3.0, 2.5
    surfaces = [
        surface((0, W), (0, D), (0, 0)),
        surface((0, W), (0, D), (H, H)),
        surface((0, 0), (0, D), (0, H)),
        surface((W, W), (0, D), (0, H)),
        surface((0, W), (0, 0), (0, H)),
        surface((0, W), (D, D), (0, H)),
    ]
    all_pts = np.vstack(surfaces)

    lines = [f"{x:.6f} {y:.6f} {z:.6f} 180 180 180" for x, y, z in all_pts]
    return ("\n".join(lines) + "\n").encode()


def upload_payload(project_id: str, name: str = "room.xyz", kind: str = "xyz", content: bytes = b"1 1 1 1 1 1\n"):
    data = {"project_id": project_id, "name": name, "captured_at": "2026-08-15", "kind": kind, "source_up_axis": "y"}
    files = {"file": (name, content, "application/octet-stream")}
    return data, files


async def test_generate_ifc_from_synthetic_room(client: AsyncClient, project: Project):
    content = _build_synthetic_room_xyz()
    data, files = upload_payload(str(project.id), content=content)
    created = (await client.post("/api/v1/site-captures/", data=data, files=files)).json()
    assert created["kind"] == "xyz"

    resp = await client.post(f"/api/v1/site-captures/{created['id']}/generate-ifc")
    assert resp.status_code == 200, resp.text
    model3d = resp.json()
    assert model3d["kind"] == "ifc"
    assert model3d["project_id"] == str(project.id)
    assert model3d["source_up_axis"] == "z"
    assert model3d["size_bytes"] > 0

    download = await client.get(f"/api/v1/model3d-files/{model3d['id']}/download")
    assert download.status_code == 200

    # Genuinely parse the generated bytes with ifcopenshell — not just
    # "the endpoint returned 200" — and confirm real geometry was detected,
    # not an empty/degenerate model.
    import tempfile
    from pathlib import Path
    with tempfile.TemporaryDirectory() as tmp:
        ifc_path = Path(tmp) / "result.ifc"
        ifc_path.write_bytes(download.content)
        ifc_file = ifcopenshell.open(str(ifc_path))
        assert ifc_file.schema == "IFC4"
        assert len(ifc_file.by_type("IfcWall")) == 4
        assert len(ifc_file.by_type("IfcSlab")) == 2
        assert len(ifc_file.by_type("IfcSpace")) == 1


async def test_generate_ifc_replaces_prior_result_on_rerun(client: AsyncClient, project: Project):
    content = _build_synthetic_room_xyz()
    data, files = upload_payload(str(project.id), content=content)
    created = (await client.post("/api/v1/site-captures/", data=data, files=files)).json()

    first = (await client.post(f"/api/v1/site-captures/{created['id']}/generate-ifc")).json()
    second = (await client.post(f"/api/v1/site-captures/{created['id']}/generate-ifc")).json()

    # Re-running "Generate IFC" replaces the prior Model3DFile (same name +
    # kind), same convention as any other re-import — not a second,
    # accumulating row (see model3d_file.py's own create_file docstring).
    listing = (await client.get("/api/v1/model3d-files/", params={"project_id": str(project.id)})).json()
    matching = [f for f in listing if f["name"] == first["name"]]
    assert len(matching) == 1
    assert matching[0]["id"] == second["id"]
    assert first["id"] != second["id"]


async def test_generate_ifc_on_e57_capture_400s(client: AsyncClient, project: Project):
    data, files = upload_payload(str(project.id), name="raw.e57", kind="e57", content=b"not-a-real-e57-but-kind-is-what-matters-here")
    created = (await client.post("/api/v1/site-captures/", data=data, files=files)).json()
    assert created["kind"] == "e57"

    resp = await client.post(f"/api/v1/site-captures/{created['id']}/generate-ifc")
    assert resp.status_code == 400


async def test_generate_ifc_unknown_capture_404s(client: AsyncClient, project: Project):
    resp = await client.post(f"/api/v1/site-captures/{uuid.uuid4()}/generate-ifc")
    assert resp.status_code == 404
