"""add scope_subproject_id to scheduling_quality_runs

Revision ID: 299e01f7a78e
Revises: 747230134733
Create Date: 2026-07-06 01:46:21.721684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '299e01f7a78e'
down_revision: Union[str, None] = '747230134733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only the intended change — the autogenerated diff also picked up several
    # unrelated pre-existing unique-constraint drops on other tables (schema
    # drift already present in the dev database, nothing to do with this
    # change), stripped out here rather than folded into this migration.
    op.add_column('scheduling_quality_runs', sa.Column('scope_subproject_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_scheduling_quality_runs_scope_subproject_id', 'scheduling_quality_runs', 'schedule_subprojects',
        ['scope_subproject_id'], ['id'], ondelete='SET NULL',
    )


def downgrade() -> None:
    op.drop_constraint('fk_scheduling_quality_runs_scope_subproject_id', 'scheduling_quality_runs', type_='foreignkey')
    op.drop_column('scheduling_quality_runs', 'scope_subproject_id')
