"""add collections and collection members

Revision ID: 509510057eca
Revises: e2030c8ccaac
Create Date: 2026-07-10 12:55:54.330655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '509510057eca'
down_revision: Union[str, None] = 'e2030c8ccaac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_collection_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('source_kind', sa.String(length=10), nullable=False),
    sa.Column('element_ref', sa.String(length=300), nullable=False),
    sa.Column('element_label', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'source_kind', 'element_ref', name='uq_collection_members_collection_element')
    )
    # Autogenerate also proposed dropping/recreating several unrelated unique
    # constraints elsewhere (cost/risk/icd tables) — a metadata-rendering
    # difference (postgresql_nulls_not_distinct) versus the live DB, not a
    # real schema change this migration intends; stripped out to keep this
    # migration scoped to just the two new tables (same drift the
    # user_defined_fields migration hit, bcd42067f011).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_members')
    op.drop_table('collections')
    # ### end Alembic commands ###
