"""add baseline_sets, risk/cost/icd baselines, schedule_baselines.baseline_set_id

Revision ID: 535622165801
Revises: 80a7e7704842
Create Date: 2026-07-20 12:58:36.435857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '535622165801'
down_revision: Union[str, None] = '80a7e7704842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('baseline_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('baseline_date', sa.Date(), nullable=False),
    sa.Column('baseline_set_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_set_id'], ['baseline_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icd_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('baseline_date', sa.Date(), nullable=False),
    sa.Column('baseline_set_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_set_id'], ['baseline_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('baseline_date', sa.Date(), nullable=False),
    sa.Column('baseline_set_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_set_id'], ['baseline_sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icd_baseline_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=False),
    sa.Column('icd_item_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['icd_baselines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['icd_item_id'], ['icd_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_baseline_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('emv_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('emv_schedule_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['risk_baselines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_baseline_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=False),
    sa.Column('cost_element_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('bac', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ac', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pct_complete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['cost_baselines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_element_id'], ['cost_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('schedule_baselines', sa.Column('baseline_set_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'schedule_baselines', 'baseline_sets', ['baseline_set_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_baselines', type_='foreignkey')
    op.drop_column('schedule_baselines', 'baseline_set_id')
    op.drop_table('cost_baseline_items')
    op.drop_table('risk_baseline_items')
    op.drop_table('icd_baseline_items')
    op.drop_table('risk_baselines')
    op.drop_table('icd_baselines')
    op.drop_table('cost_baselines')
    op.drop_table('baseline_sets')
    # ### end Alembic commands ###
