"""add section_boxes table

Revision ID: 64da86406eef
Revises: f11e61ddd9cd
Create Date: 2026-07-09 18:46:31.674097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64da86406eef'
down_revision: Union[str, None] = 'f11e61ddd9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_boxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('model3d_file_id', sa.UUID(), nullable=False),
    sa.Column('element_ref', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('min_x', sa.Float(), nullable=False),
    sa.Column('min_y', sa.Float(), nullable=False),
    sa.Column('min_z', sa.Float(), nullable=False),
    sa.Column('max_x', sa.Float(), nullable=False),
    sa.Column('max_y', sa.Float(), nullable=False),
    sa.Column('max_z', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model3d_file_id'], ['model3d_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_boxes')
    # ### end Alembic commands ###
