"""add element parents table for crane-style rigging

Revision ID: 67c8a435d12f
Revises: 74d904d469cd
Create Date: 2026-07-12 20:47:37.884604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67c8a435d12f'
down_revision: Union[str, None] = '74d904d469cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_parents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('child_element_ref', sa.String(length=300), nullable=False),
    sa.Column('parent_element_ref', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'child_element_ref', name='uq_element_parents_child')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('element_parents')
    # ### end Alembic commands ###
