"""add element transforms

Revision ID: 709bb581cc0d
Revises: 509510057eca
Create Date: 2026-07-11 00:38:14.783579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '709bb581cc0d'
down_revision: Union[str, None] = '509510057eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('element_transforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('model3d_file_id', sa.UUID(), nullable=False),
    sa.Column('element_ref', sa.String(length=300), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('rotation_x', sa.Float(), nullable=False),
    sa.Column('rotation_y', sa.Float(), nullable=False),
    sa.Column('rotation_z', sa.Float(), nullable=False),
    sa.Column('scale_x', sa.Float(), nullable=False),
    sa.Column('scale_y', sa.Float(), nullable=False),
    sa.Column('scale_z', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model3d_file_id'], ['model3d_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model3d_file_id', 'element_ref', name='uq_element_transforms_file_element')
    )
    # Autogenerate also proposed dropping/recreating several unrelated unique
    # constraints elsewhere (cost/risk/icd tables) — a metadata-rendering
    # difference (postgresql_nulls_not_distinct) versus the live DB, not a
    # real schema change this migration intends; stripped out to keep this
    # migration scoped to just the new table (same drift every migration
    # this session has hit, e.g. bcd42067f011, 509510057eca).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('element_transforms')
    # ### end Alembic commands ###
