"""widen activities.wbs_role to varchar(2) for SP role

Revision ID: 747230134733
Revises: 8a0c08bb6249
Create Date: 2026-07-06 01:19:45.897058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '747230134733'
down_revision: Union[str, None] = '8a0c08bb6249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only the intended change — the autogenerated diff also picked up several
    # unrelated pre-existing unique-constraint drops on other tables (schema
    # drift already present in the dev database, nothing to do with this
    # change), stripped out here rather than folded into this migration.
    op.alter_column('activities', 'wbs_role',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=2),
               existing_nullable=False,
               existing_server_default=sa.text("'T'::character varying"))


def downgrade() -> None:
    op.alter_column('activities', 'wbs_role',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'T'::character varying"))
