"""add pivot fields to element transforms

Revision ID: 74d904d469cd
Revises: a65e5d591b8f
Create Date: 2026-07-12 20:45:32.955044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '74d904d469cd'
down_revision: Union[str, None] = 'a65e5d591b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element_transforms', sa.Column('pivot_x', sa.Float(), nullable=True))
    op.add_column('element_transforms', sa.Column('pivot_y', sa.Float(), nullable=True))
    op.add_column('element_transforms', sa.Column('pivot_z', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('element_transforms', 'pivot_z')
    op.drop_column('element_transforms', 'pivot_y')
    op.drop_column('element_transforms', 'pivot_x')
    # ### end Alembic commands ###
