"""add paths and path_followers tables

Revision ID: 753ad2a8fb11
Revises: 709bb581cc0d
Create Date: 2026-07-11 18:26:22.653683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '753ad2a8fb11'
down_revision: Union[str, None] = '709bb581cc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_followers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('target_kind', sa.String(length=10), nullable=False),
    sa.Column('element_ref', sa.String(length=300), nullable=False),
    sa.Column('orient_to_path', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'target_kind', 'element_ref', name='uq_path_followers_target')
    )
    # Note: autogenerate also proposed dropping 8 unrelated unique
    # constraints (cost/icd/risk tables) here — that's a pre-existing
    # postgresql_nulls_not_distinct metadata/DB drift, not anything this
    # migration's own models touch. Left out deliberately; not this
    # migration's job to fix.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('path_followers')
    op.drop_table('paths')
    # ### end Alembic commands ###
