"""add status field to annotation

Revision ID: 85e0613016ce
Revises: 8b7971afaf43
Create Date: 2026-07-12 13:09:48.964637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85e0613016ce'
down_revision: Union[str, None] = '8b7971afaf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand — this table already has live rows, and
    # a bare NOT NULL add_column fails against any existing row (same
    # lesson as 8b7971afaf43, two migrations up).
    op.add_column('annotations', sa.Column('status', sa.String(length=10), nullable=False, server_default='open'))
    # Autogenerate also picked up the same pre-existing
    # `postgresql_nulls_not_distinct` metadata drift on eight unrelated
    # cost/ICD/risk unique constraints seen on every previous migration
    # this session — stripped out here too, unrelated to this change.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'status')
    # ### end Alembic commands ###
