"""add annotations and comments tables

Revision ID: 85ee90005d91
Revises: 753ad2a8fb11
Create Date: 2026-07-12 11:31:19.410596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85ee90005d91'
down_revision: Union[str, None] = '753ad2a8fb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('source_kind', sa.String(length=10), nullable=True),
    sa.Column('element_ref', sa.String(length=300), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('camera_view_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_view_id'], ['camera_views.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Autogenerate also picked up a `postgresql_nulls_not_distinct` metadata
    # drift on eight unrelated cost/ICD/risk unique constraints (a known,
    # pre-existing quirk in how this schema's metadata reads back from
    # Postgres — see 753ad2a8fb11's own migration for the same drift on a
    # previous autogenerate run) — stripped out here rather than actually
    # dropping/recreating those constraints, since this migration has
    # nothing to do with them.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('annotations')
    # ### end Alembic commands ###
