"""add schedule_subprojects table and activity sub-float columns

Revision ID: 8a0c08bb6249
Revises: fae1ad54a6a0
Create Date: 2026-07-05 21:44:04.085039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8a0c08bb6249'
down_revision: Union[str, None] = 'fae1ad54a6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only the intended changes — the autogenerated diff also picked up
    # several unrelated pre-existing unique-constraint drops on other tables
    # (schema drift already present in the dev database, nothing to do with
    # this change), stripped out here rather than folded into this migration.
    op.create_table('schedule_subprojects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owning_party_org_id', sa.UUID(), nullable=True),
    sa.Column('root_wbs_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owning_party_org_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_wbs_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activities', sa.Column('owning_party_org_id', sa.UUID(), nullable=True))
    op.add_column('activities', sa.Column('sub_total_float_hours', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('activities', sa.Column('sub_is_critical', sa.Boolean(), nullable=True))
    op.create_foreign_key(
        'fk_activities_owning_party_org_id', 'activities', 'organisations', ['owning_party_org_id'], ['id'], ondelete='SET NULL'
    )


def downgrade() -> None:
    op.drop_constraint('fk_activities_owning_party_org_id', 'activities', type_='foreignkey')
    op.drop_column('activities', 'sub_is_critical')
    op.drop_column('activities', 'sub_total_float_hours')
    op.drop_column('activities', 'owning_party_org_id')
    op.drop_table('schedule_subprojects')
