"""annotation comment kind, style and behaviour fields, drop comments table

Revision ID: 8b7971afaf43
Revises: 85ee90005d91
Create Date: 2026-07-12 12:40:49.916706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8b7971afaf43'
down_revision: Union[str, None] = '85ee90005d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # server_default added by hand on every NOT NULL column below (not
    # something autogenerate writes on its own) — this table already has a
    # live row from tonight's own testing, and a bare NOT NULL add_column
    # fails against any existing row with no way to backfill it. Values
    # match each column's own Python-side default in annotation.py exactly.
    op.add_column('annotations', sa.Column('has_background', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('annotations', sa.Column('background_color', sa.String(length=9), nullable=False, server_default='#f59e0b'))
    op.add_column('annotations', sa.Column('border_color', sa.String(length=9), nullable=False, server_default='#ffffff'))
    op.add_column('annotations', sa.Column('thick_border', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('annotations', sa.Column('text_color', sa.String(length=9), nullable=False, server_default='#111827'))
    op.add_column('annotations', sa.Column('font_size', sa.Integer(), nullable=False, server_default='14'))
    op.add_column('annotations', sa.Column('hide_closer_than', sa.Float(), nullable=True))
    op.add_column('annotations', sa.Column('hide_farther_than', sa.Float(), nullable=True))
    # background_color takes over from the old single `color` field
    # (2026-07-12) — copy existing values across before dropping it, rather
    # than silently discarding whatever colour was already set.
    op.execute("UPDATE annotations SET background_color = color")
    op.drop_column('annotations', 'color')
    # Autogenerate also picked up the same pre-existing
    # `postgresql_nulls_not_distinct` metadata drift on eight unrelated
    # cost/ICD/risk unique constraints seen on every previous migration
    # this session (753ad2a8fb11, 85ee90005d91) — stripped out here too,
    # this migration has nothing to do with them.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('color', sa.VARCHAR(length=9), autoincrement=False, nullable=False, server_default='#f59e0b'))
    op.execute("UPDATE annotations SET color = background_color")
    op.drop_column('annotations', 'hide_farther_than')
    op.drop_column('annotations', 'hide_closer_than')
    op.drop_column('annotations', 'font_size')
    op.drop_column('annotations', 'text_color')
    op.drop_column('annotations', 'thick_border')
    op.drop_column('annotations', 'border_color')
    op.drop_column('annotations', 'background_color')
    op.drop_column('annotations', 'has_background')
    op.create_table('comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('camera_view_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_view_id'], ['camera_views.id'], name='comments_camera_view_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='comments_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    # ### end Alembic commands ###
