"""add user defined fields

Revision ID: bcd42067f011
Revises: 7454efae2a86
Create Date: 2026-07-07 09:03:19.223112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bcd42067f011'
down_revision: Union[str, None] = '7454efae2a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_defined_field_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'entity_type', 'name', name='uq_udf_definition_project_entity_name')
    )
    op.create_table('user_defined_field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_definition_id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('value_indicator', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['field_definition_id'], ['user_defined_field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_definition_id', 'record_id', name='uq_udf_value_field_record')
    )
    # Autogenerate also proposed dropping/recreating several unrelated unique
    # constraints elsewhere (cost/risk/icd tables) — a metadata-rendering
    # difference (postgresql_nulls_not_distinct) versus the live DB, not a
    # real schema change this migration intends; stripped out to keep this
    # migration scoped to just the two new tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_defined_field_values')
    op.drop_table('user_defined_field_definitions')
    # ### end Alembic commands ###
