"""add activity status column

Revision ID: d90be24d117e
Revises: b4f19e2c7a3d
Create Date: 2026-09-03 10:30:03.413100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'd90be24d117e'
down_revision: Union[str, None] = 'b4f19e2c7a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not the raw autogenerate output (2026-09-03) — the
# autogenerated diff also picked up a large amount of unrelated pre-existing
# drift between this dev DB and the models (dropping the feedback_tickets
# tables, several unrelated unique constraints) that has nothing to do with
# this column and would have been a real, unrelated, destructive change if
# ever applied to production — stripped down to just the one real change.


def upgrade() -> None:
    # server_default is temporary, only so the NOT NULL constraint below can
    # be satisfied for every already-existing row in one pass — removed again
    # at the end so new rows keep going through the ORM-level default (see
    # app/models/activity.py's own `default="planned"`, same as activity_type
    # already does, not a DB-level default).
    op.add_column('activities', sa.Column('status', sa.String(length=20), nullable=False, server_default='planned'))
    # Backfill existing rows with the real status a straight 'planned'
    # default would get wrong — the exact same 4-state derivation
    # app/services/activity.py:_derive_activity_status uses (mirrored here in
    # SQL since this needs to run once, directly against the table, for
    # every activity that already existed before this column did).
    op.execute("""
        UPDATE activities SET status = CASE
            WHEN activity_type IN ('start_milestone', 'finish_milestone') THEN
                CASE WHEN COALESCE(pct_complete, 0) >= 100 THEN 'completed' ELSE 'planned' END
            WHEN COALESCE(pct_complete, 0) >= 100 THEN 'completed'
            WHEN suspend_date IS NOT NULL AND resume_date IS NULL THEN 'suspended'
            WHEN COALESCE(pct_complete, 0) > 0 OR actual_start IS NOT NULL THEN 'in_progress'
            ELSE 'planned'
        END
    """)
    op.alter_column('activities', 'status', server_default=None)


def downgrade() -> None:
    op.drop_column('activities', 'status')
