"""add camera_views table

Revision ID: e2030c8ccaac
Revises: 64da86406eef
Create Date: 2026-07-10 00:08:00.140197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2030c8ccaac'
down_revision: Union[str, None] = '64da86406eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('target_x', sa.Float(), nullable=False),
    sa.Column('target_y', sa.Float(), nullable=False),
    sa.Column('target_z', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera_views')
    # ### end Alembic commands ###
