"""add model3d_files table

Revision ID: f11e61ddd9cd
Revises: 9b95b37a181b
Create Date: 2026-07-09 17:21:14.350469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f11e61ddd9cd'
down_revision: Union[str, None] = '9b95b37a181b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model3d_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source_up_axis', sa.String(length=1), nullable=False),
    sa.Column('storage_filename', sa.String(length=300), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_filename')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model3d_files')
    # ### end Alembic commands ###
