"""add scheduling_filters table

Revision ID: fae1ad54a6a0
Revises: d7a3e5c1f048
Create Date: 2026-07-05 19:10:01.996488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fae1ad54a6a0'
down_revision: Union[str, None] = 'd7a3e5c1f048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only the new table — the autogenerated diff also picked up several
    # unrelated pre-existing unique-constraint drops on other tables (schema
    # drift already present in the dev database, nothing to do with this
    # change), stripped out here rather than folded into this migration.
    op.create_table('scheduling_filters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('match_mode', sa.String(length=3), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('scheduling_filters')
